// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Certificate.proto

package com.sdpm.smart.farming.devicemgr.certificate;

public final class CertificateProto {
  private CertificateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CertificateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Certificate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 deviceId = 1;</code>
     * @return The deviceId.
     */
    int getDeviceId();

    /**
     * <code>string url = 2;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <code>string url = 2;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>int32 qos = 3;</code>
     * @return The qos.
     */
    int getQos();

    /**
     * <code>string username = 4;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 4;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string password = 5;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 5;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string clientId = 6;</code>
     * @return The clientId.
     */
    java.lang.String getClientId();
    /**
     * <code>string clientId = 6;</code>
     * @return The bytes for clientId.
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string eventTopic = 7;</code>
     * @return The eventTopic.
     */
    java.lang.String getEventTopic();
    /**
     * <code>string eventTopic = 7;</code>
     * @return The bytes for eventTopic.
     */
    com.google.protobuf.ByteString
        getEventTopicBytes();

    /**
     * <code>string commandTopic = 8;</code>
     * @return The commandTopic.
     */
    java.lang.String getCommandTopic();
    /**
     * <code>string commandTopic = 8;</code>
     * @return The bytes for commandTopic.
     */
    com.google.protobuf.ByteString
        getCommandTopicBytes();

    /**
     * <code>string rtcVideoClientId = 9;</code>
     * @return The rtcVideoClientId.
     */
    java.lang.String getRtcVideoClientId();
    /**
     * <code>string rtcVideoClientId = 9;</code>
     * @return The bytes for rtcVideoClientId.
     */
    com.google.protobuf.ByteString
        getRtcVideoClientIdBytes();

    /**
     * <code>string rtcVideoReqTopic = 10;</code>
     * @return The rtcVideoReqTopic.
     */
    java.lang.String getRtcVideoReqTopic();
    /**
     * <code>string rtcVideoReqTopic = 10;</code>
     * @return The bytes for rtcVideoReqTopic.
     */
    com.google.protobuf.ByteString
        getRtcVideoReqTopicBytes();

    /**
     * <code>string rtcVideoAnsTopic = 11;</code>
     * @return The rtcVideoAnsTopic.
     */
    java.lang.String getRtcVideoAnsTopic();
    /**
     * <code>string rtcVideoAnsTopic = 11;</code>
     * @return The bytes for rtcVideoAnsTopic.
     */
    com.google.protobuf.ByteString
        getRtcVideoAnsTopicBytes();

    /**
     * <code>string rtcDataClientId = 12;</code>
     * @return The rtcDataClientId.
     */
    java.lang.String getRtcDataClientId();
    /**
     * <code>string rtcDataClientId = 12;</code>
     * @return The bytes for rtcDataClientId.
     */
    com.google.protobuf.ByteString
        getRtcDataClientIdBytes();

    /**
     * <code>string rtcDataReqTopic = 13;</code>
     * @return The rtcDataReqTopic.
     */
    java.lang.String getRtcDataReqTopic();
    /**
     * <code>string rtcDataReqTopic = 13;</code>
     * @return The bytes for rtcDataReqTopic.
     */
    com.google.protobuf.ByteString
        getRtcDataReqTopicBytes();

    /**
     * <code>string rtcDataAnsTopic = 14;</code>
     * @return The rtcDataAnsTopic.
     */
    java.lang.String getRtcDataAnsTopic();
    /**
     * <code>string rtcDataAnsTopic = 14;</code>
     * @return The bytes for rtcDataAnsTopic.
     */
    com.google.protobuf.ByteString
        getRtcDataAnsTopicBytes();

    /**
     * <code>string iceServerUrls = 15;</code>
     * @return The iceServerUrls.
     */
    java.lang.String getIceServerUrls();
    /**
     * <code>string iceServerUrls = 15;</code>
     * @return The bytes for iceServerUrls.
     */
    com.google.protobuf.ByteString
        getIceServerUrlsBytes();

    /**
     * <code>string iceServerUsername = 16;</code>
     * @return The iceServerUsername.
     */
    java.lang.String getIceServerUsername();
    /**
     * <code>string iceServerUsername = 16;</code>
     * @return The bytes for iceServerUsername.
     */
    com.google.protobuf.ByteString
        getIceServerUsernameBytes();

    /**
     * <code>string iceServerCredential = 17;</code>
     * @return The iceServerCredential.
     */
    java.lang.String getIceServerCredential();
    /**
     * <code>string iceServerCredential = 17;</code>
     * @return The bytes for iceServerCredential.
     */
    com.google.protobuf.ByteString
        getIceServerCredentialBytes();
  }
  /**
   * Protobuf type {@code Certificate}
   */
  public  static final class Certificate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Certificate)
      CertificateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Certificate.newBuilder() to construct.
    private Certificate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Certificate() {
      url_ = "";
      username_ = "";
      password_ = "";
      clientId_ = "";
      eventTopic_ = "";
      commandTopic_ = "";
      rtcVideoClientId_ = "";
      rtcVideoReqTopic_ = "";
      rtcVideoAnsTopic_ = "";
      rtcDataClientId_ = "";
      rtcDataReqTopic_ = "";
      rtcDataAnsTopic_ = "";
      iceServerUrls_ = "";
      iceServerUsername_ = "";
      iceServerCredential_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Certificate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Certificate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              deviceId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 24: {

              qos_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              eventTopic_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              commandTopic_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              rtcVideoClientId_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              rtcVideoReqTopic_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              rtcVideoAnsTopic_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              rtcDataClientId_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              rtcDataReqTopic_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              rtcDataAnsTopic_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              iceServerUrls_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              iceServerUsername_ = s;
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              iceServerCredential_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.internal_static_Certificate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.internal_static_Certificate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate.class, com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate.Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private int deviceId_;
    /**
     * <code>int32 deviceId = 1;</code>
     * @return The deviceId.
     */
    public int getDeviceId() {
      return deviceId_;
    }

    public static final int URL_FIELD_NUMBER = 2;
    private volatile java.lang.Object url_;
    /**
     * <code>string url = 2;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 2;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QOS_FIELD_NUMBER = 3;
    private int qos_;
    /**
     * <code>int32 qos = 3;</code>
     * @return The qos.
     */
    public int getQos() {
      return qos_;
    }

    public static final int USERNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object username_;
    /**
     * <code>string username = 4;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 4;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 5;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 5;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 5;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTID_FIELD_NUMBER = 6;
    private volatile java.lang.Object clientId_;
    /**
     * <code>string clientId = 6;</code>
     * @return The clientId.
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string clientId = 6;</code>
     * @return The bytes for clientId.
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTTOPIC_FIELD_NUMBER = 7;
    private volatile java.lang.Object eventTopic_;
    /**
     * <code>string eventTopic = 7;</code>
     * @return The eventTopic.
     */
    public java.lang.String getEventTopic() {
      java.lang.Object ref = eventTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventTopic_ = s;
        return s;
      }
    }
    /**
     * <code>string eventTopic = 7;</code>
     * @return The bytes for eventTopic.
     */
    public com.google.protobuf.ByteString
        getEventTopicBytes() {
      java.lang.Object ref = eventTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMANDTOPIC_FIELD_NUMBER = 8;
    private volatile java.lang.Object commandTopic_;
    /**
     * <code>string commandTopic = 8;</code>
     * @return The commandTopic.
     */
    public java.lang.String getCommandTopic() {
      java.lang.Object ref = commandTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commandTopic_ = s;
        return s;
      }
    }
    /**
     * <code>string commandTopic = 8;</code>
     * @return The bytes for commandTopic.
     */
    public com.google.protobuf.ByteString
        getCommandTopicBytes() {
      java.lang.Object ref = commandTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commandTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RTCVIDEOCLIENTID_FIELD_NUMBER = 9;
    private volatile java.lang.Object rtcVideoClientId_;
    /**
     * <code>string rtcVideoClientId = 9;</code>
     * @return The rtcVideoClientId.
     */
    public java.lang.String getRtcVideoClientId() {
      java.lang.Object ref = rtcVideoClientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtcVideoClientId_ = s;
        return s;
      }
    }
    /**
     * <code>string rtcVideoClientId = 9;</code>
     * @return The bytes for rtcVideoClientId.
     */
    public com.google.protobuf.ByteString
        getRtcVideoClientIdBytes() {
      java.lang.Object ref = rtcVideoClientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtcVideoClientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RTCVIDEOREQTOPIC_FIELD_NUMBER = 10;
    private volatile java.lang.Object rtcVideoReqTopic_;
    /**
     * <code>string rtcVideoReqTopic = 10;</code>
     * @return The rtcVideoReqTopic.
     */
    public java.lang.String getRtcVideoReqTopic() {
      java.lang.Object ref = rtcVideoReqTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtcVideoReqTopic_ = s;
        return s;
      }
    }
    /**
     * <code>string rtcVideoReqTopic = 10;</code>
     * @return The bytes for rtcVideoReqTopic.
     */
    public com.google.protobuf.ByteString
        getRtcVideoReqTopicBytes() {
      java.lang.Object ref = rtcVideoReqTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtcVideoReqTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RTCVIDEOANSTOPIC_FIELD_NUMBER = 11;
    private volatile java.lang.Object rtcVideoAnsTopic_;
    /**
     * <code>string rtcVideoAnsTopic = 11;</code>
     * @return The rtcVideoAnsTopic.
     */
    public java.lang.String getRtcVideoAnsTopic() {
      java.lang.Object ref = rtcVideoAnsTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtcVideoAnsTopic_ = s;
        return s;
      }
    }
    /**
     * <code>string rtcVideoAnsTopic = 11;</code>
     * @return The bytes for rtcVideoAnsTopic.
     */
    public com.google.protobuf.ByteString
        getRtcVideoAnsTopicBytes() {
      java.lang.Object ref = rtcVideoAnsTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtcVideoAnsTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RTCDATACLIENTID_FIELD_NUMBER = 12;
    private volatile java.lang.Object rtcDataClientId_;
    /**
     * <code>string rtcDataClientId = 12;</code>
     * @return The rtcDataClientId.
     */
    public java.lang.String getRtcDataClientId() {
      java.lang.Object ref = rtcDataClientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtcDataClientId_ = s;
        return s;
      }
    }
    /**
     * <code>string rtcDataClientId = 12;</code>
     * @return The bytes for rtcDataClientId.
     */
    public com.google.protobuf.ByteString
        getRtcDataClientIdBytes() {
      java.lang.Object ref = rtcDataClientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtcDataClientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RTCDATAREQTOPIC_FIELD_NUMBER = 13;
    private volatile java.lang.Object rtcDataReqTopic_;
    /**
     * <code>string rtcDataReqTopic = 13;</code>
     * @return The rtcDataReqTopic.
     */
    public java.lang.String getRtcDataReqTopic() {
      java.lang.Object ref = rtcDataReqTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtcDataReqTopic_ = s;
        return s;
      }
    }
    /**
     * <code>string rtcDataReqTopic = 13;</code>
     * @return The bytes for rtcDataReqTopic.
     */
    public com.google.protobuf.ByteString
        getRtcDataReqTopicBytes() {
      java.lang.Object ref = rtcDataReqTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtcDataReqTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RTCDATAANSTOPIC_FIELD_NUMBER = 14;
    private volatile java.lang.Object rtcDataAnsTopic_;
    /**
     * <code>string rtcDataAnsTopic = 14;</code>
     * @return The rtcDataAnsTopic.
     */
    public java.lang.String getRtcDataAnsTopic() {
      java.lang.Object ref = rtcDataAnsTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rtcDataAnsTopic_ = s;
        return s;
      }
    }
    /**
     * <code>string rtcDataAnsTopic = 14;</code>
     * @return The bytes for rtcDataAnsTopic.
     */
    public com.google.protobuf.ByteString
        getRtcDataAnsTopicBytes() {
      java.lang.Object ref = rtcDataAnsTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rtcDataAnsTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICESERVERURLS_FIELD_NUMBER = 15;
    private volatile java.lang.Object iceServerUrls_;
    /**
     * <code>string iceServerUrls = 15;</code>
     * @return The iceServerUrls.
     */
    public java.lang.String getIceServerUrls() {
      java.lang.Object ref = iceServerUrls_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iceServerUrls_ = s;
        return s;
      }
    }
    /**
     * <code>string iceServerUrls = 15;</code>
     * @return The bytes for iceServerUrls.
     */
    public com.google.protobuf.ByteString
        getIceServerUrlsBytes() {
      java.lang.Object ref = iceServerUrls_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iceServerUrls_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICESERVERUSERNAME_FIELD_NUMBER = 16;
    private volatile java.lang.Object iceServerUsername_;
    /**
     * <code>string iceServerUsername = 16;</code>
     * @return The iceServerUsername.
     */
    public java.lang.String getIceServerUsername() {
      java.lang.Object ref = iceServerUsername_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iceServerUsername_ = s;
        return s;
      }
    }
    /**
     * <code>string iceServerUsername = 16;</code>
     * @return The bytes for iceServerUsername.
     */
    public com.google.protobuf.ByteString
        getIceServerUsernameBytes() {
      java.lang.Object ref = iceServerUsername_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iceServerUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICESERVERCREDENTIAL_FIELD_NUMBER = 17;
    private volatile java.lang.Object iceServerCredential_;
    /**
     * <code>string iceServerCredential = 17;</code>
     * @return The iceServerCredential.
     */
    public java.lang.String getIceServerCredential() {
      java.lang.Object ref = iceServerCredential_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iceServerCredential_ = s;
        return s;
      }
    }
    /**
     * <code>string iceServerCredential = 17;</code>
     * @return The bytes for iceServerCredential.
     */
    public com.google.protobuf.ByteString
        getIceServerCredentialBytes() {
      java.lang.Object ref = iceServerCredential_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iceServerCredential_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (deviceId_ != 0) {
        output.writeInt32(1, deviceId_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, url_);
      }
      if (qos_ != 0) {
        output.writeInt32(3, qos_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, username_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, password_);
      }
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, clientId_);
      }
      if (!getEventTopicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, eventTopic_);
      }
      if (!getCommandTopicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, commandTopic_);
      }
      if (!getRtcVideoClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, rtcVideoClientId_);
      }
      if (!getRtcVideoReqTopicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, rtcVideoReqTopic_);
      }
      if (!getRtcVideoAnsTopicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, rtcVideoAnsTopic_);
      }
      if (!getRtcDataClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, rtcDataClientId_);
      }
      if (!getRtcDataReqTopicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, rtcDataReqTopic_);
      }
      if (!getRtcDataAnsTopicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, rtcDataAnsTopic_);
      }
      if (!getIceServerUrlsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, iceServerUrls_);
      }
      if (!getIceServerUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, iceServerUsername_);
      }
      if (!getIceServerCredentialBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, iceServerCredential_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (deviceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deviceId_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, url_);
      }
      if (qos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, qos_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, username_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, password_);
      }
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, clientId_);
      }
      if (!getEventTopicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, eventTopic_);
      }
      if (!getCommandTopicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, commandTopic_);
      }
      if (!getRtcVideoClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, rtcVideoClientId_);
      }
      if (!getRtcVideoReqTopicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, rtcVideoReqTopic_);
      }
      if (!getRtcVideoAnsTopicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, rtcVideoAnsTopic_);
      }
      if (!getRtcDataClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, rtcDataClientId_);
      }
      if (!getRtcDataReqTopicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, rtcDataReqTopic_);
      }
      if (!getRtcDataAnsTopicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, rtcDataAnsTopic_);
      }
      if (!getIceServerUrlsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, iceServerUrls_);
      }
      if (!getIceServerUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, iceServerUsername_);
      }
      if (!getIceServerCredentialBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, iceServerCredential_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate)) {
        return super.equals(obj);
      }
      com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate other = (com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate) obj;

      if (getDeviceId()
          != other.getDeviceId()) return false;
      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (getQos()
          != other.getQos()) return false;
      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (!getEventTopic()
          .equals(other.getEventTopic())) return false;
      if (!getCommandTopic()
          .equals(other.getCommandTopic())) return false;
      if (!getRtcVideoClientId()
          .equals(other.getRtcVideoClientId())) return false;
      if (!getRtcVideoReqTopic()
          .equals(other.getRtcVideoReqTopic())) return false;
      if (!getRtcVideoAnsTopic()
          .equals(other.getRtcVideoAnsTopic())) return false;
      if (!getRtcDataClientId()
          .equals(other.getRtcDataClientId())) return false;
      if (!getRtcDataReqTopic()
          .equals(other.getRtcDataReqTopic())) return false;
      if (!getRtcDataAnsTopic()
          .equals(other.getRtcDataAnsTopic())) return false;
      if (!getIceServerUrls()
          .equals(other.getIceServerUrls())) return false;
      if (!getIceServerUsername()
          .equals(other.getIceServerUsername())) return false;
      if (!getIceServerCredential()
          .equals(other.getIceServerCredential())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + QOS_FIELD_NUMBER;
      hash = (53 * hash) + getQos();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + EVENTTOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getEventTopic().hashCode();
      hash = (37 * hash) + COMMANDTOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getCommandTopic().hashCode();
      hash = (37 * hash) + RTCVIDEOCLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getRtcVideoClientId().hashCode();
      hash = (37 * hash) + RTCVIDEOREQTOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getRtcVideoReqTopic().hashCode();
      hash = (37 * hash) + RTCVIDEOANSTOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getRtcVideoAnsTopic().hashCode();
      hash = (37 * hash) + RTCDATACLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getRtcDataClientId().hashCode();
      hash = (37 * hash) + RTCDATAREQTOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getRtcDataReqTopic().hashCode();
      hash = (37 * hash) + RTCDATAANSTOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getRtcDataAnsTopic().hashCode();
      hash = (37 * hash) + ICESERVERURLS_FIELD_NUMBER;
      hash = (53 * hash) + getIceServerUrls().hashCode();
      hash = (37 * hash) + ICESERVERUSERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getIceServerUsername().hashCode();
      hash = (37 * hash) + ICESERVERCREDENTIAL_FIELD_NUMBER;
      hash = (53 * hash) + getIceServerCredential().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Certificate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Certificate)
        com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.CertificateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.internal_static_Certificate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.internal_static_Certificate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate.class, com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate.Builder.class);
      }

      // Construct using com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceId_ = 0;

        url_ = "";

        qos_ = 0;

        username_ = "";

        password_ = "";

        clientId_ = "";

        eventTopic_ = "";

        commandTopic_ = "";

        rtcVideoClientId_ = "";

        rtcVideoReqTopic_ = "";

        rtcVideoAnsTopic_ = "";

        rtcDataClientId_ = "";

        rtcDataReqTopic_ = "";

        rtcDataAnsTopic_ = "";

        iceServerUrls_ = "";

        iceServerUsername_ = "";

        iceServerCredential_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.internal_static_Certificate_descriptor;
      }

      @java.lang.Override
      public com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate getDefaultInstanceForType() {
        return com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate.getDefaultInstance();
      }

      @java.lang.Override
      public com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate build() {
        com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate buildPartial() {
        com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate result = new com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate(this);
        result.deviceId_ = deviceId_;
        result.url_ = url_;
        result.qos_ = qos_;
        result.username_ = username_;
        result.password_ = password_;
        result.clientId_ = clientId_;
        result.eventTopic_ = eventTopic_;
        result.commandTopic_ = commandTopic_;
        result.rtcVideoClientId_ = rtcVideoClientId_;
        result.rtcVideoReqTopic_ = rtcVideoReqTopic_;
        result.rtcVideoAnsTopic_ = rtcVideoAnsTopic_;
        result.rtcDataClientId_ = rtcDataClientId_;
        result.rtcDataReqTopic_ = rtcDataReqTopic_;
        result.rtcDataAnsTopic_ = rtcDataAnsTopic_;
        result.iceServerUrls_ = iceServerUrls_;
        result.iceServerUsername_ = iceServerUsername_;
        result.iceServerCredential_ = iceServerCredential_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate) {
          return mergeFrom((com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate other) {
        if (other == com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate.getDefaultInstance()) return this;
        if (other.getDeviceId() != 0) {
          setDeviceId(other.getDeviceId());
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.getQos() != 0) {
          setQos(other.getQos());
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getEventTopic().isEmpty()) {
          eventTopic_ = other.eventTopic_;
          onChanged();
        }
        if (!other.getCommandTopic().isEmpty()) {
          commandTopic_ = other.commandTopic_;
          onChanged();
        }
        if (!other.getRtcVideoClientId().isEmpty()) {
          rtcVideoClientId_ = other.rtcVideoClientId_;
          onChanged();
        }
        if (!other.getRtcVideoReqTopic().isEmpty()) {
          rtcVideoReqTopic_ = other.rtcVideoReqTopic_;
          onChanged();
        }
        if (!other.getRtcVideoAnsTopic().isEmpty()) {
          rtcVideoAnsTopic_ = other.rtcVideoAnsTopic_;
          onChanged();
        }
        if (!other.getRtcDataClientId().isEmpty()) {
          rtcDataClientId_ = other.rtcDataClientId_;
          onChanged();
        }
        if (!other.getRtcDataReqTopic().isEmpty()) {
          rtcDataReqTopic_ = other.rtcDataReqTopic_;
          onChanged();
        }
        if (!other.getRtcDataAnsTopic().isEmpty()) {
          rtcDataAnsTopic_ = other.rtcDataAnsTopic_;
          onChanged();
        }
        if (!other.getIceServerUrls().isEmpty()) {
          iceServerUrls_ = other.iceServerUrls_;
          onChanged();
        }
        if (!other.getIceServerUsername().isEmpty()) {
          iceServerUsername_ = other.iceServerUsername_;
          onChanged();
        }
        if (!other.getIceServerCredential().isEmpty()) {
          iceServerCredential_ = other.iceServerCredential_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int deviceId_ ;
      /**
       * <code>int32 deviceId = 1;</code>
       * @return The deviceId.
       */
      public int getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>int32 deviceId = 1;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(int value) {
        
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 deviceId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        
        deviceId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>string url = 2;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string url = 2;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 2;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 2;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private int qos_ ;
      /**
       * <code>int32 qos = 3;</code>
       * @return The qos.
       */
      public int getQos() {
        return qos_;
      }
      /**
       * <code>int32 qos = 3;</code>
       * @param value The qos to set.
       * @return This builder for chaining.
       */
      public Builder setQos(int value) {
        
        qos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 qos = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQos() {
        
        qos_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 4;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 4;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 4;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string username = 4;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 5;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 5;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 5;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 5;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>string clientId = 6;</code>
       * @return The clientId.
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientId = 6;</code>
       * @return The bytes for clientId.
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientId = 6;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string clientId = 6;</code>
       * @param value The bytes for clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object eventTopic_ = "";
      /**
       * <code>string eventTopic = 7;</code>
       * @return The eventTopic.
       */
      public java.lang.String getEventTopic() {
        java.lang.Object ref = eventTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventTopic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string eventTopic = 7;</code>
       * @return The bytes for eventTopic.
       */
      public com.google.protobuf.ByteString
          getEventTopicBytes() {
        java.lang.Object ref = eventTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string eventTopic = 7;</code>
       * @param value The eventTopic to set.
       * @return This builder for chaining.
       */
      public Builder setEventTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string eventTopic = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventTopic() {
        
        eventTopic_ = getDefaultInstance().getEventTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string eventTopic = 7;</code>
       * @param value The bytes for eventTopic to set.
       * @return This builder for chaining.
       */
      public Builder setEventTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventTopic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object commandTopic_ = "";
      /**
       * <code>string commandTopic = 8;</code>
       * @return The commandTopic.
       */
      public java.lang.String getCommandTopic() {
        java.lang.Object ref = commandTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commandTopic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string commandTopic = 8;</code>
       * @return The bytes for commandTopic.
       */
      public com.google.protobuf.ByteString
          getCommandTopicBytes() {
        java.lang.Object ref = commandTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commandTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string commandTopic = 8;</code>
       * @param value The commandTopic to set.
       * @return This builder for chaining.
       */
      public Builder setCommandTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commandTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string commandTopic = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommandTopic() {
        
        commandTopic_ = getDefaultInstance().getCommandTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string commandTopic = 8;</code>
       * @param value The bytes for commandTopic to set.
       * @return This builder for chaining.
       */
      public Builder setCommandTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commandTopic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rtcVideoClientId_ = "";
      /**
       * <code>string rtcVideoClientId = 9;</code>
       * @return The rtcVideoClientId.
       */
      public java.lang.String getRtcVideoClientId() {
        java.lang.Object ref = rtcVideoClientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rtcVideoClientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rtcVideoClientId = 9;</code>
       * @return The bytes for rtcVideoClientId.
       */
      public com.google.protobuf.ByteString
          getRtcVideoClientIdBytes() {
        java.lang.Object ref = rtcVideoClientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rtcVideoClientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rtcVideoClientId = 9;</code>
       * @param value The rtcVideoClientId to set.
       * @return This builder for chaining.
       */
      public Builder setRtcVideoClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rtcVideoClientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rtcVideoClientId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtcVideoClientId() {
        
        rtcVideoClientId_ = getDefaultInstance().getRtcVideoClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string rtcVideoClientId = 9;</code>
       * @param value The bytes for rtcVideoClientId to set.
       * @return This builder for chaining.
       */
      public Builder setRtcVideoClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rtcVideoClientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rtcVideoReqTopic_ = "";
      /**
       * <code>string rtcVideoReqTopic = 10;</code>
       * @return The rtcVideoReqTopic.
       */
      public java.lang.String getRtcVideoReqTopic() {
        java.lang.Object ref = rtcVideoReqTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rtcVideoReqTopic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rtcVideoReqTopic = 10;</code>
       * @return The bytes for rtcVideoReqTopic.
       */
      public com.google.protobuf.ByteString
          getRtcVideoReqTopicBytes() {
        java.lang.Object ref = rtcVideoReqTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rtcVideoReqTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rtcVideoReqTopic = 10;</code>
       * @param value The rtcVideoReqTopic to set.
       * @return This builder for chaining.
       */
      public Builder setRtcVideoReqTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rtcVideoReqTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rtcVideoReqTopic = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtcVideoReqTopic() {
        
        rtcVideoReqTopic_ = getDefaultInstance().getRtcVideoReqTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string rtcVideoReqTopic = 10;</code>
       * @param value The bytes for rtcVideoReqTopic to set.
       * @return This builder for chaining.
       */
      public Builder setRtcVideoReqTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rtcVideoReqTopic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rtcVideoAnsTopic_ = "";
      /**
       * <code>string rtcVideoAnsTopic = 11;</code>
       * @return The rtcVideoAnsTopic.
       */
      public java.lang.String getRtcVideoAnsTopic() {
        java.lang.Object ref = rtcVideoAnsTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rtcVideoAnsTopic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rtcVideoAnsTopic = 11;</code>
       * @return The bytes for rtcVideoAnsTopic.
       */
      public com.google.protobuf.ByteString
          getRtcVideoAnsTopicBytes() {
        java.lang.Object ref = rtcVideoAnsTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rtcVideoAnsTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rtcVideoAnsTopic = 11;</code>
       * @param value The rtcVideoAnsTopic to set.
       * @return This builder for chaining.
       */
      public Builder setRtcVideoAnsTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rtcVideoAnsTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rtcVideoAnsTopic = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtcVideoAnsTopic() {
        
        rtcVideoAnsTopic_ = getDefaultInstance().getRtcVideoAnsTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string rtcVideoAnsTopic = 11;</code>
       * @param value The bytes for rtcVideoAnsTopic to set.
       * @return This builder for chaining.
       */
      public Builder setRtcVideoAnsTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rtcVideoAnsTopic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rtcDataClientId_ = "";
      /**
       * <code>string rtcDataClientId = 12;</code>
       * @return The rtcDataClientId.
       */
      public java.lang.String getRtcDataClientId() {
        java.lang.Object ref = rtcDataClientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rtcDataClientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rtcDataClientId = 12;</code>
       * @return The bytes for rtcDataClientId.
       */
      public com.google.protobuf.ByteString
          getRtcDataClientIdBytes() {
        java.lang.Object ref = rtcDataClientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rtcDataClientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rtcDataClientId = 12;</code>
       * @param value The rtcDataClientId to set.
       * @return This builder for chaining.
       */
      public Builder setRtcDataClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rtcDataClientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rtcDataClientId = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtcDataClientId() {
        
        rtcDataClientId_ = getDefaultInstance().getRtcDataClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string rtcDataClientId = 12;</code>
       * @param value The bytes for rtcDataClientId to set.
       * @return This builder for chaining.
       */
      public Builder setRtcDataClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rtcDataClientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rtcDataReqTopic_ = "";
      /**
       * <code>string rtcDataReqTopic = 13;</code>
       * @return The rtcDataReqTopic.
       */
      public java.lang.String getRtcDataReqTopic() {
        java.lang.Object ref = rtcDataReqTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rtcDataReqTopic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rtcDataReqTopic = 13;</code>
       * @return The bytes for rtcDataReqTopic.
       */
      public com.google.protobuf.ByteString
          getRtcDataReqTopicBytes() {
        java.lang.Object ref = rtcDataReqTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rtcDataReqTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rtcDataReqTopic = 13;</code>
       * @param value The rtcDataReqTopic to set.
       * @return This builder for chaining.
       */
      public Builder setRtcDataReqTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rtcDataReqTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rtcDataReqTopic = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtcDataReqTopic() {
        
        rtcDataReqTopic_ = getDefaultInstance().getRtcDataReqTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string rtcDataReqTopic = 13;</code>
       * @param value The bytes for rtcDataReqTopic to set.
       * @return This builder for chaining.
       */
      public Builder setRtcDataReqTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rtcDataReqTopic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rtcDataAnsTopic_ = "";
      /**
       * <code>string rtcDataAnsTopic = 14;</code>
       * @return The rtcDataAnsTopic.
       */
      public java.lang.String getRtcDataAnsTopic() {
        java.lang.Object ref = rtcDataAnsTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rtcDataAnsTopic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rtcDataAnsTopic = 14;</code>
       * @return The bytes for rtcDataAnsTopic.
       */
      public com.google.protobuf.ByteString
          getRtcDataAnsTopicBytes() {
        java.lang.Object ref = rtcDataAnsTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rtcDataAnsTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rtcDataAnsTopic = 14;</code>
       * @param value The rtcDataAnsTopic to set.
       * @return This builder for chaining.
       */
      public Builder setRtcDataAnsTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rtcDataAnsTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rtcDataAnsTopic = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtcDataAnsTopic() {
        
        rtcDataAnsTopic_ = getDefaultInstance().getRtcDataAnsTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string rtcDataAnsTopic = 14;</code>
       * @param value The bytes for rtcDataAnsTopic to set.
       * @return This builder for chaining.
       */
      public Builder setRtcDataAnsTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rtcDataAnsTopic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object iceServerUrls_ = "";
      /**
       * <code>string iceServerUrls = 15;</code>
       * @return The iceServerUrls.
       */
      public java.lang.String getIceServerUrls() {
        java.lang.Object ref = iceServerUrls_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iceServerUrls_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string iceServerUrls = 15;</code>
       * @return The bytes for iceServerUrls.
       */
      public com.google.protobuf.ByteString
          getIceServerUrlsBytes() {
        java.lang.Object ref = iceServerUrls_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iceServerUrls_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string iceServerUrls = 15;</code>
       * @param value The iceServerUrls to set.
       * @return This builder for chaining.
       */
      public Builder setIceServerUrls(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iceServerUrls_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string iceServerUrls = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearIceServerUrls() {
        
        iceServerUrls_ = getDefaultInstance().getIceServerUrls();
        onChanged();
        return this;
      }
      /**
       * <code>string iceServerUrls = 15;</code>
       * @param value The bytes for iceServerUrls to set.
       * @return This builder for chaining.
       */
      public Builder setIceServerUrlsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iceServerUrls_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object iceServerUsername_ = "";
      /**
       * <code>string iceServerUsername = 16;</code>
       * @return The iceServerUsername.
       */
      public java.lang.String getIceServerUsername() {
        java.lang.Object ref = iceServerUsername_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iceServerUsername_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string iceServerUsername = 16;</code>
       * @return The bytes for iceServerUsername.
       */
      public com.google.protobuf.ByteString
          getIceServerUsernameBytes() {
        java.lang.Object ref = iceServerUsername_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iceServerUsername_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string iceServerUsername = 16;</code>
       * @param value The iceServerUsername to set.
       * @return This builder for chaining.
       */
      public Builder setIceServerUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iceServerUsername_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string iceServerUsername = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearIceServerUsername() {
        
        iceServerUsername_ = getDefaultInstance().getIceServerUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string iceServerUsername = 16;</code>
       * @param value The bytes for iceServerUsername to set.
       * @return This builder for chaining.
       */
      public Builder setIceServerUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iceServerUsername_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object iceServerCredential_ = "";
      /**
       * <code>string iceServerCredential = 17;</code>
       * @return The iceServerCredential.
       */
      public java.lang.String getIceServerCredential() {
        java.lang.Object ref = iceServerCredential_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iceServerCredential_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string iceServerCredential = 17;</code>
       * @return The bytes for iceServerCredential.
       */
      public com.google.protobuf.ByteString
          getIceServerCredentialBytes() {
        java.lang.Object ref = iceServerCredential_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iceServerCredential_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string iceServerCredential = 17;</code>
       * @param value The iceServerCredential to set.
       * @return This builder for chaining.
       */
      public Builder setIceServerCredential(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iceServerCredential_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string iceServerCredential = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearIceServerCredential() {
        
        iceServerCredential_ = getDefaultInstance().getIceServerCredential();
        onChanged();
        return this;
      }
      /**
       * <code>string iceServerCredential = 17;</code>
       * @param value The bytes for iceServerCredential to set.
       * @return This builder for chaining.
       */
      public Builder setIceServerCredentialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iceServerCredential_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Certificate)
    }

    // @@protoc_insertion_point(class_scope:Certificate)
    private static final com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate();
    }

    public static com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Certificate>
        PARSER = new com.google.protobuf.AbstractParser<Certificate>() {
      @java.lang.Override
      public Certificate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Certificate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Certificate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Certificate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sdpm.smart.farming.devicemgr.certificate.CertificateProto.Certificate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Certificate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Certificate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Certificate.proto\"\201\003\n\013Certificate\022\020\n\010d" +
      "eviceId\030\001 \001(\005\022\013\n\003url\030\002 \001(\t\022\013\n\003qos\030\003 \001(\005\022" +
      "\020\n\010username\030\004 \001(\t\022\020\n\010password\030\005 \001(\t\022\020\n\010c" +
      "lientId\030\006 \001(\t\022\022\n\neventTopic\030\007 \001(\t\022\024\n\014com" +
      "mandTopic\030\010 \001(\t\022\030\n\020rtcVideoClientId\030\t \001(" +
      "\t\022\030\n\020rtcVideoReqTopic\030\n \001(\t\022\030\n\020rtcVideoA" +
      "nsTopic\030\013 \001(\t\022\027\n\017rtcDataClientId\030\014 \001(\t\022\027" +
      "\n\017rtcDataReqTopic\030\r \001(\t\022\027\n\017rtcDataAnsTop" +
      "ic\030\016 \001(\t\022\025\n\riceServerUrls\030\017 \001(\t\022\031\n\021iceSe" +
      "rverUsername\030\020 \001(\t\022\033\n\023iceServerCredentia" +
      "l\030\021 \001(\tB@\n,com.sdpm.smart.farming.device" +
      "mgr.certificateB\020CertificateProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Certificate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Certificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Certificate_descriptor,
        new java.lang.String[] { "DeviceId", "Url", "Qos", "Username", "Password", "ClientId", "EventTopic", "CommandTopic", "RtcVideoClientId", "RtcVideoReqTopic", "RtcVideoAnsTopic", "RtcDataClientId", "RtcDataReqTopic", "RtcDataAnsTopic", "IceServerUrls", "IceServerUsername", "IceServerCredential", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
